stages:
  - test

run_tests:
  stage: test
  image: mcr.microsoft.com/playwright/python:v1.61.0-jammy
  script:
    - pip install -r requirements.txt
    - pytest --tracing retain-on-failure --output=test-results
  artifacts:
    when: always
    paths:
      - test-results/
    expire_in: 1 week
